{
	"intro": {
		"title": "Welcome to the IBM Openlabs trial. Here you will find step-by-step learning guides to help you build integrations in minutes as well as additional resources.",
		"content": "intro.md"
	},
	"tasks": [{
			"title": "Build and Integrate APIs",
			"content": "task1.md"
		},
		{
			"title": "Openlabs Cheatsheet",
			"content": "task2.md"
		}
	]
}